### ISSUE TITLE
Unable to run npm run build

### ISSUE THREAD

**Issue by skyhip0811** [Atinux/nuxt-todos-edge#12]
when running npm run build. 
I got following error. 

ERROR  [vite:vue] Could not load ~/node_modules/nuxt-icon/dist/runtime/IconCSS.vue?vue&type=style&index=0&scoped=41e8d397&lang.css?inline&used: ENOENT: no such file or directory, open '\\?~\node_modules\nuxt-icon\dist\runtime\IconCSS.vue'

**Comment by Atinux** [comment]
It works fine on my end, can you try again by upgrading the deps?
