### ISSUE TITLE
Drizzle Studios is not displayed in DevTools after signing in with GitHub

### ISSUE THREAD

**Issue by Rednas83** [Atinux/nuxt-todos-edge#14]
**DevTools**
![image](https://github.com/Atinux/nuxt-todos-edge/assets/25219229/37c14c75-ac2f-40d3-bdca-ffbf68953410)
**Terminal**
![image](https://github.com/Atinux/nuxt-todos-edge/assets/25219229/1020a7e2-6af3-4f0b-9931-4fb497912aaa)
**Console.log**
![image](https://github.com/Atinux/nuxt-todos-edge/assets/25219229/a1023937-3da6-47c5-8967-1b5ffcffc45f)

**Tried**
Upgrading to the latest nuxt with the latest packages

**Comment by Atinux** [comment]
It works for me, I pushed with latest deps update:
![CleanShot 2024-01-24 at 13 05 14@2x](https://github.com/Atinux/nuxt-todos-edge/assets/904724/f304500c-d8bd-4dc6-8048-31755e97b322)
