### ISSUE TITLE
Add typesafe communication with trpc

### ISSUE THREAD

**Issue by Rednas83** [Atinux/nuxt-todos-edge#15]
Is it also an idea to add typesafe communication to the template?
https://github.com/wobsoriano/trpc-nuxt
https://trpc.io/

**Comment by Atinux** [comment]
We already have typesafe communication with Nuxt 3 without the need for an external library.

![CleanShot 2024-01-24 at 13 03 40@2x](https://github.com/Atinux/nuxt-todos-edge/assets/904724/e51bc320-d9ac-4644-a073-2584d5635581)

**Comment by Atinux** [comment]
I understand but the goal of this template is to showcase fullstack development with Nuxt.

**Comment by Rednas83** [comment]
Fair enough. Thanks for the response
