### ISSUE TITLE
Deploying to Azure Static Web App

### ISSUE THREAD

**Issue by mushtaq** [Atinux/nuxt-todos-edge#16]
Thanks for creating this end-to-end demo of Nuxt3.

After removing the auth related code, I could successfully deploy it to Azure using [the docs](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs).

But I am really struggling to make it work with auth code. 

The issue is, redirect_uri sent by SWA to github does not match the callback url specified in the Github OAuth aap.

I thought [this setting](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#forwarding-gateway) may help, but tweaking it has not helped so far.

It will be great, if the README includes guidance on deploying to Azure as well.

**Comment by Atinux** [comment]
Sorry for the late answer, did you check https://github.com/atinux/nuxt-auth-utils ?
