### ISSUE TITLE
Database isn't re-queried for updates when mutating or adding data

### ISSUE THREAD

**Issue by daleweaver777** [Atinux/nuxt-todos-edge#17]
It looks like the database isn't re-queried for updates when mutating or adding data.

Example:
Open two browser windows with the same login. Add a new todo in window 1. Then go to window 2 and add another new todo. You would expect window 2 to not only add it's own todo, but also now show the todo that window 1 entered. If you do a hard refresh in window 2, the todo entered in window 1 will now show.

When posting, patching, or deleting to an endpoint, shouldn't a fresh copy of the todo's be retrieved from the database instead of just adding the changes to the in-memory array?

**Comment by Atinux** [comment]
I updated to call `refresh` :)
