### ISSUE TITLE
Why can't I access properties of the user inside the <script> tags?

### ISSUE THREAD

**Issue by Woolfe** [Atinux/nuxt-todos-edge#20]
In `todos.vue` if I change ```toast.add({ title: `Todo "${todo.title}" created.` })``` to ```toast.add({ title: `Todo "${todo.title}" created by ${user.login}.` })``` it will show as undefined, but the property is accessible inside the template.

I'm coming from Nuxt 2 so this might be me misunderstanding how SSR works in Nuxt 3. Why aren't the properties of `user` accessible here and how would I go about exposing them? 

I apologise if this is the wrong place to ask this question.

**Comment by Atinux** [comment]
You need to use `${user.value.login}` and `${todo.value.title}`.

I highly recommend you to read more about Vue 3 at first.
