### ISSUE TITLE
Convert this to a protected and public page

### ISSUE THREAD

**Issue by fayazara** [Atinux/nuxt-todos-edge#3]
A protected page example could be more realistic and practical. 

I will try to make a PR which does this with a middleware on a page called `/todos`

**Comment by Atinux** [comment]
Why do you think it will be more practical?

Happy to see a PR to showcase more features yes

**Comment by fayazara** [comment]
@Atinux I think this is what a typical app looks like: some public pages, such as the home page, pricing page, and some protected ones, like the profile page and dashboard. 

I am working on a PR, will share soon.
