### ISSUE TITLE
Broken production build

### ISSUE THREAD

**Issue by fayazara** [Atinux/nuxt-todos-edge#4]
I connected D1 in settings and it throws this error in the console, any idea, what's causing this?

![Screenshot 18-05 at 10](https://github.com/Atinux/nuxt-todos-edge/assets/15716057/5fa54910-b2c2-4bdb-8706-015ac1eb002c)

Demo - https://nuxt-todos-edge-5ij.pages.dev/
Code - https://github.com/fayazara/nuxt-todos-edge/

**Comment by fayazara** [comment]
Works perfectly in local btw

**Comment by Atinux** [comment]
You may want to add copy/paste the migrations in your D1 database in the console:
<img width="889" alt="CleanShot 2023-05-18 at 12 03 00@2x" src="https://github.com/Atinux/nuxt-todos-edge/assets/904724/3e823e00-3d1b-4f1d-b94b-adfe9448668c">

**Comment by fayazara** [comment]
How do I do this?

**Comment by Atinux** [comment]
You create a D1 database, open the console of it.

Then copy the content of https://github.com/Atinux/nuxt-todos-edge/blob/main/server/db/migrations/0000_sloppy_starfox.sql in it

**Comment by fayazara** [comment]
Worked, thanks !!
